all:
  vars:
    ansible_connection: network_cli
    ansible_user: admin
    ansible_network_os: ios
  children:
    # TESTSWTS:
    #   hosts:
    #     TESTSWT01:
    #       ansible_host: 192.168.45.10
    #     TESTSWT02:
    #       ansible_host: 192.168.45.11
    AUTH:
      hosts:
        AUTHSWT01:
          ansible_host: 192.168.45.100
        AUTHSWT02:
          ansible_host: 192.168.45.200
    DC01:
      hosts:
        DC01SWT01:
          ansible_host: 192.168.100.1
        DC01SWT02:
          ansible_host: 192.168.100.102
        DC01SWT03:
          ansible_host: 192.168.100.103
        DC01SWT04:
          ansible_host: 192.168.100.104
    DC02:
      hosts:
        DC02SWT01:
          ansible_host: 192.168.200.1
        DC02SWT03:
          ansible_host: 192.168.200.103
        DC02SWT04:
          ansible_host: 192.168.200.104
    CCPD:
      hosts:
        CCPDSWT01:
          ansible_host: 192.168.68.1
    CSPD:
      hosts:
        CSPDSWT01:
          ansible_host: 192.168.61.1
        CSPDSWTEVEN:
          ansible_host: 192.168.61.3
        CSPDSWTLGHTBR:
          ansible_host: 192.168.61.4
        CSPDSWTODDS:
          ansible_host: 192.168.61.2
        CSPDSWTTRN:
          ansible_host: 192.168.61.5
    EPSO:
      hosts:
        EPSOSWT01:
          ansible_host: 192.168.62.1
        EPSOSWTLGHTBR:
          ansible_host: 192.168.62.2
        EPSOSWTTRN:
          ansible_host: 192.168.62.3
    FCFD:
      hosts:
        FCFDSWT01:
          ansible_host: 192.168.63.1
    PAFB:
      hosts:
        PAFBSWT01:
          ansible_host: 192.168.64.1
    CMAF:
      hosts:
        CMAFSWT01:
          ansible_host: 192.168.65.1
        CMAFSWT02:
          ansible_host: 192.168.65.2
        CMAFSWT03:
          ansible_host: 192.168.65.3
    TCSO:
      hosts:
        TCSOSWT01:
          ansible_host: 192.168.67.1
    WPPD:
      hosts:
        WPPDSWT01:
          ansible_host: 192.168.66.1