---


- name: "Connectivity Check"
  hosts: all
  gather_facts: false
  vars_files:
    - vars/passwords.yml
  vars:
      ansible_password: "{{ host_passwords[inventory_hostname] | default( group_passwords[group_names[0]] ) }}"

  tasks:

    - name: "Ansible built ping test"
      ansible.builtin.ping:



